application: appname
version: 1
runtime: python27
api_version: 1
threadsafe: yes


handlers:

- url: /css
  static_dir: assets/css

- url: /img
  static_dir: assets/img

- url: /js
  static_dir: assets/js

- url: /favicon.ico
  static_files: assets/favicon.ico
  upload: assets/favicon.ico

- url: /robots.txt
  static_files: assets/robots.txt
  upload: assets/robots.txt

- url: /humans.txt
  static_files: assets/humans.txt
  upload: assets/humans.txt

- url: /apple-touch-icon-114x114-precomposed.png
  static_files: assets/apple-touch-icon-114x114-precomposed.png
  upload: assets/apple-touch-icon-114x114-precomposed.png

- url: /apple-touch-icon-144x144-precomposed.png
  static_files: assets/apple-touch-icon-144x144-precomposed.png
  upload: assets/apple-touch-icon-144x144-precomposed.png

- url: /apple-touch-icon-57x57-precomposed.png
  static_files: assets/apple-touch-icon-57x57-precomposed.png
  upload: assets/apple-touch-icon-57x57-precomposed.png

- url: /apple-touch-icon-72x72-precomposed.png
  static_files: assets/apple-touch-icon-72x72-precomposed.png
  upload: assets/apple-touch-icon-72x72-precomposed.png

- url: /apple-touch-icon.png
  static_files: assets/apple-touch-icon.png
  upload: assets/apple-touch-icon.png

- url: /api
  script: main.api

- url: /.*
  script: main.app


libraries:

- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: "2.6"
